#!/bin/sh
#                               -*- Mode: Sh -*- 
# config --- 
# Author           : Manoj Srivastava ( srivasta@glaurung.green-gryphon.com ) 
# Created On       : Fri Oct 31 21:53:31 2003
# Created On Node  : glaurung.green-gryphon.com
# Last Modified By : Manoj Srivastava
# Last Modified On : Mon Apr 19 01:41:21 2004
# Last Machine Used: glaurung.internal.golden-gryphon.com
# Update Count     : 16
# Status           : Unknown, Use with caution!
# HISTORY          : 
# Description      : 
# arch-tag: 1c40a2eb-f28c-41b5-a423-671be2e816ed
# 

set -e

case "$1" in
  configure)
    # Configure this package.  If the package must prompt the user for
    # information, do it here.
	if [ ! -e /etc/news/organization ]; then
	    if [ -e /usr/share/debconf/confmodule ]; then
		. /usr/share/debconf/confmodule
		db_capb
		ok=''
		# See if the old shared question still exists.
		if db_get share/news/organization; then
		    if [ "X$RET" != "X" ]; then
			ok=1
			break
		    fi
		fi
		while [ ! "$ok" ]; do
		    retval=$(db_input low  shared/news/organization) || true
		    if [ "$retval" = "30 question skipped" ]; then
			ok=1
		    fi
		    db_go || true
		    db_get shared/news/organization
		    if [ "X$RET" != "X" ]; then
			ok=1
			break
		    fi
		done
	    fi
	fi

    ;;
  reconfigure)
	if [ ! -e /etc/news/organization ]; then
	    if [ -e /usr/share/debconf/confmodule ]; then
		. /usr/share/debconf/confmodule
		db_capb
		ok=''
		# See if the old shared question still exists.
		if db_get share/news/organization; then
		    if [ "X$RET" != "X" ]; then
			ok=1
			break
		    fi
		fi
		while [ ! "$ok" ]; do
		    retval=$(db_input low  shared/news/organization) || true
		    if [ "$retval" = "30 question skipped" ]; then
			ok=1
		    fi
		    db_go || true
		    db_get shared/news/organization
		    if [ "X$RET" != "X" ]; then
			ok=1
			break
		    fi
		done
	    fi
	fi
    ;;
  *) echo "$0: didn't understand being called with \`$1'" 1>&2
     exit 0;;
esac

exit 0;

